"""Pydantic models for CLI output and internal representation."""

from libspec.cli.models.lifecycle import (
    ApprovalEvidence,
    BenchmarkEvidence,
    BlockedItem,
    CustomEvidence,
    DeprecationNoticeEvidence,
    DesignDocEvidence,
    DevStateSpec,
    DevTransitionSpec,
    DocsEvidence,
    # Evidence types
    EvidenceSpec,
    EvidenceTypeSpec,
    GateSpec,
    GateStatus,
    LifecycleEntity,
    # Entity types
    LifecycleFields,
    LifecycleLibraryFields,
    MigrationGuideEvidence,
    PrEvidence,
    TestsEvidence,
    # Workflow types
    WorkflowSpec,
)
from libspec.cli.models.lint import (
    LintIssue,
    LintMeta,
    LintResult,
    Severity,
)
from libspec.cli.models.output import (
    CountsResult,
    CoverageResult,
    FeatureSummary,
    FunctionSummary,
    InfoResult,
    LibraryInfo,
    ModuleSummary,
    OutputEnvelope,
    PrincipleSummary,
    SpecContext,
    TypeSummary,
)

__all__ = [
    "OutputEnvelope",
    "SpecContext",
    "TypeSummary",
    "FunctionSummary",
    "FeatureSummary",
    "ModuleSummary",
    "PrincipleSummary",
    "InfoResult",
    "CountsResult",
    "CoverageResult",
    "LibraryInfo",
    "Severity",
    "LintIssue",
    "LintResult",
    "LintMeta",
    # Lifecycle types
    "EvidenceSpec",
    "PrEvidence",
    "TestsEvidence",
    "DesignDocEvidence",
    "DocsEvidence",
    "ApprovalEvidence",
    "BenchmarkEvidence",
    "MigrationGuideEvidence",
    "DeprecationNoticeEvidence",
    "CustomEvidence",
    "WorkflowSpec",
    "DevStateSpec",
    "DevTransitionSpec",
    "GateSpec",
    "EvidenceTypeSpec",
    "LifecycleFields",
    "LifecycleLibraryFields",
    "LifecycleEntity",
    "BlockedItem",
    "GateStatus",
]
