# generated by datamodel-codegen:
#   filename:  cli.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from libspec.models.base import ExtensionModel
from pydantic import Field, RootModel, conint


class CliExtension(RootModel[Any]):
    root: Any = Field(
        ...,
        description='Extension for command-line interfaces: commands, arguments, options, subcommands.',
        title='CLI Extension',
    )


class ExampleSpec(ExtensionModel):
    command: str | None = Field(None, description='Example command line')
    description: str | None = Field(None, description='What this example demonstrates')
    output: str | None = Field(None, description='Expected output')


class ExitCodeSpec(ExtensionModel):
    code: conint(ge=0, le=255) = Field(..., description='Exit code value')
    name: str | None = Field(None, description='Exit code name')
    description: str | None = Field(None, description='When this code is returned')


class Shell(Enum):
    bash = 'bash'
    zsh = 'zsh'
    fish = 'fish'
    powershell = 'powershell'


class ShellCompletionSpec(ExtensionModel):
    shells: list[Shell] | None = Field(None, description='Supported shells')
    install_command: str | None = Field(
        None, description='Command to install completions'
    )
    env_var: str | None = Field(
        None, description='Environment variable for completion script'
    )


class Type(Enum):
    path = 'path'
    file = 'file'
    directory = 'directory'
    choice = 'choice'
    dynamic = 'dynamic'
    none = 'none'


class CompletionSpec(ExtensionModel):
    type: Type | None = Field(None, description='Completion type')
    function: str | None = Field(
        None, description='Custom completion function reference'
    )
    file_pattern: str | None = Field(
        None, description='File pattern for path completion'
    )


class Color(Enum):
    auto = 'auto'
    always = 'always'
    never = 'never'


class HelpFormattingSpec(ExtensionModel):
    max_width: conint(ge=1) | None = Field(None, description='Maximum help text width')
    show_default: bool | None = Field(
        None, description='Show defaults in help by default'
    )
    show_envvar: bool | None = Field(
        None, description='Show env vars in help by default'
    )
    rich_markup: bool | None = Field(
        None, description='Whether rich markup is supported'
    )
    color: Color | None = Field(None, description='Color support')


class ContextSettingsSpec(ExtensionModel):
    allow_extra_args: bool | None = Field(
        None, description='Whether extra arguments are allowed'
    )
    allow_interspersed_args: bool | None = Field(
        None, description='Whether args can be mixed with options'
    )
    ignore_unknown_options: bool | None = Field(
        None, description='Whether unknown options are ignored'
    )
    auto_envvar_prefix: str | None = Field(
        None, description='Auto-generate envvar names with prefix'
    )
    token_normalize_func: str | None = Field(
        None, description='Function to normalize tokens'
    )


class ArgumentSpec(ExtensionModel):
    name: str = Field(..., description='Argument name')
    type: str | None = Field(None, description='Argument type')
    required: bool | None = Field(True, description='Whether argument is required')
    default: Any | None = Field(None, description='Default value')
    nargs: int | str | None = Field(
        None, description="Number of arguments (int, '?', '*', '+')"
    )
    metavar: str | None = Field(None, description='Display name in help')
    help: str | None = Field(None, description='Help text')
    envvar: str | None = Field(None, description='Environment variable fallback')
    shell_complete: CompletionSpec | None = None


class OptionSpec(ExtensionModel):
    name: str = Field(..., description="Long option name (e.g., '--verbose')")
    short: str | None = Field(None, description="Short option name (e.g., '-v')")
    type: str | None = Field(None, description='Option type')
    required: bool | None = Field(False, description='Whether option is required')
    default: Any | None = Field(None, description='Default value')
    is_flag: bool | None = Field(None, description='Whether this is a boolean flag')
    flag_value: Any | None = Field(None, description='Value when flag is set')
    count: bool | None = Field(
        None, description='Whether to count occurrences (e.g., -vvv)'
    )
    multiple: bool | None = Field(None, description='Whether option can be repeated')
    choices: list | None = Field(None, description='Valid choices')
    metavar: str | None = Field(None, description='Display name in help')
    help: str | None = Field(None, description='Help text')
    hidden: bool | None = Field(None, description='Whether option is hidden from help')
    envvar: str | None = Field(None, description='Environment variable name')
    prompt: bool | str | None = Field(
        None, description='Whether to prompt if not provided'
    )
    confirmation_prompt: bool | None = Field(
        None, description='Whether to confirm input'
    )
    hide_input: bool | None = Field(
        None, description='Whether to hide input (for passwords)'
    )
    show_default: bool | None = Field(
        None, description='Whether to show default in help'
    )
    show_envvar: bool | None = Field(None, description='Whether to show envvar in help')
    shell_complete: CompletionSpec | None = None


class CommandSpec(ExtensionModel):
    name: str = Field(..., description='Command name')
    aliases: list[str] | None = Field(None, description='Command aliases')
    handler: str | None = Field(None, description='Handler function reference')
    arguments: list[ArgumentSpec] | None = Field(
        None, description='Positional arguments'
    )
    options: list[OptionSpec] | None = Field(None, description='Command options/flags')
    subcommands: list[CommandSpec] | None = Field(None, description='Subcommands')
    help: str | None = Field(None, description='Help text')
    short_help: str | None = Field(
        None, description='Short help shown in command listings'
    )
    epilog: str | None = Field(None, description='Text shown after help')
    hidden: bool | None = Field(None, description='Whether command is hidden from help')
    deprecated: bool | None = Field(None, description='Whether command is deprecated')
    deprecated_message: str | None = Field(None, description='Deprecation message')
    examples: list[ExampleSpec] | None = Field(None, description='Usage examples')
    context_settings: ContextSettingsSpec | None = None


class CLILibraryFields(ExtensionModel):
    cli_name: str | None = Field(None, description='CLI executable name')
    commands: list[CommandSpec] | None = Field(None, description='CLI commands')
    global_options: list[OptionSpec] | None = Field(
        None, description='Options available to all commands'
    )
    shell_completion: ShellCompletionSpec | None = None
    help_formatting: HelpFormattingSpec | None = None
    exit_codes: list[ExitCodeSpec] | None = Field(
        None, description='Exit code definitions'
    )


CommandSpec.model_rebuild()
