# generated by datamodel-codegen:
#   filename:  events.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from libspec.models.base import ExtensionModel
from pydantic import Field, RootModel, confloat, conint


class EventsExtension(RootModel[Any]):
    root: Any = Field(
        ...,
        description='Extension for event-driven architectures: events, handlers, buses, pub/sub.',
        title='Events Extension',
    )


class EventsTypeFields(ExtensionModel):
    emits: list[str] | None = Field(None, description='Events this type emits')
    handles: list[str] | None = Field(None, description='Events this type handles')
    domain_events: bool | None = Field(
        None, description='Whether this is a domain event aggregate'
    )


class EventsMethodFields(ExtensionModel):
    emits: list[str] | None = Field(None, description='Events this method emits')
    triggers_on: list[str] | None = Field(
        None, description='Events that trigger this method'
    )


class Category(Enum):
    domain = 'domain'
    integration = 'integration'
    notification = 'notification'
    system = 'system'
    command = 'command'
    query = 'query'


class EventFieldSpec(ExtensionModel):
    name: str = Field(..., description='Field name')
    type: str = Field(..., description='Field type')
    required: bool | None = Field(True, description='Whether field is required')
    description: str | None = None


class Ordering(Enum):
    none = 'none'
    fifo = 'fifo'
    partition_fifo = 'partition_fifo'


class Backoff(Enum):
    fixed = 'fixed'
    exponential = 'exponential'
    linear = 'linear'
    fibonacci = 'fibonacci'


class RetrySpec(ExtensionModel):
    max_attempts: conint(ge=1) | None = Field(
        None, description='Maximum retry attempts'
    )
    backoff: Backoff | None = Field(None, description='Backoff strategy')
    initial_delay: confloat(ge=0.0) | None = Field(
        None, description='Initial delay in seconds'
    )
    max_delay: confloat(ge=0.0) | None = Field(
        None, description='Maximum delay in seconds'
    )
    jitter: bool | None = Field(None, description='Whether to add jitter')
    retryable_exceptions: list[str] | None = Field(
        None, description='Exceptions that trigger retry'
    )


class Operator(Enum):
    eq = 'eq'
    neq = 'neq'
    gt = 'gt'
    gte = 'gte'
    lt = 'lt'
    lte = 'lte'
    in_ = 'in'
    contains = 'contains'
    regex = 'regex'


class EventFilterSpec(ExtensionModel):
    field: str | None = Field(None, description='Field to filter on')
    operator: Operator | None = Field(None, description='Filter operator')
    value: Any | None = Field(None, description='Filter value')


class Type(Enum):
    in_memory = 'in_memory'
    redis = 'redis'
    rabbitmq = 'rabbitmq'
    kafka = 'kafka'
    sqs = 'sqs'
    pubsub = 'pubsub'
    nats = 'nats'
    custom = 'custom'


class OrderingGuarantee(Enum):
    none = 'none'
    per_partition = 'per_partition'
    global_ = 'global'


class EventBusSpec(ExtensionModel):
    type: Type | None = Field(None, description='Event bus type')
    async_dispatch: bool | None = Field(None, description='Whether dispatch is async')
    guaranteed_delivery: bool | None = Field(
        None, description='Whether delivery is guaranteed'
    )
    ordering_guarantee: OrderingGuarantee | None = Field(
        None, description='Ordering guarantee level'
    )
    at_least_once: bool | None = Field(None, description='At-least-once delivery')
    at_most_once: bool | None = Field(None, description='At-most-once delivery')
    exactly_once: bool | None = Field(None, description='Exactly-once delivery')
    transactional_outbox: bool | None = Field(
        None, description='Whether transactional outbox pattern is supported'
    )
    event_sourcing: bool | None = Field(
        None, description='Whether event sourcing is supported'
    )


class TopicSpec(ExtensionModel):
    name: str = Field(..., description='Topic name')
    pattern: str | None = Field(None, description='Topic pattern (for wildcards)')
    partitions: conint(ge=1) | None = Field(None, description='Number of partitions')
    retention: str | None = Field(None, description='Message retention period')
    events: list[str] | None = Field(
        None, description='Event types published to this topic'
    )
    subscribers: list[str] | None = Field(None, description='Subscriber handler names')
    description: str | None = None


class Persistence(Enum):
    in_memory = 'in_memory'
    database = 'database'
    event_store = 'event_store'


class OnFailure(Enum):
    compensate = 'compensate'
    retry = 'retry'
    skip = 'skip'
    abort = 'abort'


class SagaStepSpec(ExtensionModel):
    name: str = Field(..., description='Step name')
    action: str | None = Field(None, description='Action to perform (command/event)')
    wait_for: list[str] | None = Field(None, description='Events to wait for')
    timeout: confloat(ge=0.0) | None = Field(
        None, description='Step timeout in seconds'
    )
    on_failure: OnFailure | None = Field(None, description='Failure handling')


class CompensationSpec(ExtensionModel):
    step: str = Field(..., description='Step to compensate')
    action: str = Field(..., description='Compensation action')
    idempotent: bool | None = Field(
        None, description='Whether compensation is idempotent'
    )


class EventSpec(ExtensionModel):
    name: str = Field(..., description='Event type name')
    type: str | None = Field(None, description='Event class reference')
    category: Category | None = Field(None, description='Event category')
    payload: list[EventFieldSpec] | None = Field(
        None, description='Event payload fields'
    )
    metadata: list[EventFieldSpec] | None = Field(
        None, description='Standard metadata fields'
    )
    topic: str | None = Field(None, description='Default topic/channel')
    version: str | None = Field(None, description='Event schema version')
    idempotency_key: str | None = Field(None, description='Field used for idempotency')
    ordering_key: str | None = Field(None, description='Field used for ordering')
    ttl: str | None = Field(None, description='Event time-to-live')
    description: str | None = None


class HandlerSpec(ExtensionModel):
    name: str = Field(..., description='Handler name')
    handles: list[str] | None = Field(None, description='Events this handler processes')
    function: str | None = Field(None, description='Handler function reference')
    async_: bool | None = Field(
        None, alias='async', description='Whether handler is async'
    )
    retry: RetrySpec | None = None
    timeout: confloat(ge=0.0) | None = Field(
        None, description='Handler timeout in seconds'
    )
    concurrency: conint(ge=1) | None = Field(
        None, description='Max concurrent executions'
    )
    ordering: Ordering | None = Field(None, description='Event ordering guarantee')
    idempotent: bool | None = Field(None, description='Whether handler is idempotent')
    dead_letter: str | None = Field(None, description='Dead letter topic on failure')
    filters: list[EventFilterSpec] | None = Field(None, description='Event filters')
    description: str | None = None


class SagaSpec(ExtensionModel):
    name: str = Field(..., description='Saga name')
    type: str | None = Field(None, description='Saga class reference')
    starts_with: list[str] | None = Field(
        None, description='Events that start this saga'
    )
    steps: list[SagaStepSpec] | None = Field(None, description='Saga steps')
    compensations: list[CompensationSpec] | None = Field(
        None, description='Compensation actions'
    )
    timeout: confloat(ge=0.0) | None = Field(
        None, description='Saga timeout in seconds'
    )
    persistence: Persistence | None = Field(
        None, description='State persistence strategy'
    )
    description: str | None = None


class EventsLibraryFields(ExtensionModel):
    events: list[EventSpec] | None = Field(None, description='Event type definitions')
    handlers: list[HandlerSpec] | None = Field(
        None, description='Event handler definitions'
    )
    event_bus: EventBusSpec | None = None
    topics: list[TopicSpec] | None = Field(
        None, description='Topic/channel definitions'
    )
    sagas: list[SagaSpec] | None = Field(
        None, description='Saga/process manager definitions'
    )
