# generated by datamodel-codegen:
#   filename:  testing.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any

from libspec.models.base import ExtensionModel
from pydantic import Field, RootModel, confloat


class TestingExtension(RootModel[Any]):
    root: Any = Field(
        ...,
        description='Extension for testing utilities: fixtures, mocks, test patterns, assertions.',
        title='Testing Extension',
    )


class Scope(Enum):
    function = 'function'
    class_ = 'class'
    module = 'module'
    package = 'package'
    session = 'session'


class FixtureSpec(ExtensionModel):
    name: str = Field(..., description='Fixture name')
    scope: Scope | None = Field(None, description='Fixture scope')
    type: str | None = Field(None, description='Return type')
    factory: str | None = Field(None, description='Factory function reference')
    dependencies: list[str] | None = Field(
        None, description='Other fixtures this depends on'
    )
    autouse: bool | None = Field(
        None, description='Whether fixture is automatically used'
    )
    params: list | None = Field(None, description='Parameterization values')
    yields: bool | None = Field(
        None, description='Whether fixture uses yield (generator)'
    )
    async_: bool | None = Field(
        None, alias='async', description='Whether fixture is async'
    )
    cleanup: str | None = Field(None, description='Cleanup behavior description')
    description: str | None = None


class Type(Enum):
    mock = 'mock'
    stub = 'stub'
    spy = 'spy'
    fake = 'fake'
    dummy = 'dummy'


class MockSpec(ExtensionModel):
    name: str = Field(..., description='Mock utility name')
    type: Type | None = Field(None, description='Mock type')
    target: str | None = Field(None, description='What this mocks (type reference)')
    factory: str | None = Field(None, description='Factory function reference')
    configurable: list[str] | None = Field(None, description='Configurable behaviors')
    auto_spec: bool | None = Field(
        None, description='Whether spec is auto-generated from target'
    )
    description: str | None = None


class FactoryFieldSpec(ExtensionModel):
    name: str = Field(..., description='Field name')
    default: Any | None = Field(None, description='Default value or generator')
    faker: str | None = Field(
        None, description="Faker provider (e.g., 'name', 'email')"
    )
    sequence: bool | None = Field(None, description='Whether this is a sequence')
    lazy: bool | None = Field(None, description='Whether value is lazily evaluated')
    subfactory: str | None = Field(None, description='Subfactory reference')


class TraitSpec(ExtensionModel):
    name: str = Field(..., description='Trait name')
    overrides: dict[str, Any] | None = Field(None, description='Field overrides')
    description: str | None = None


class SequenceSpec(ExtensionModel):
    name: str = Field(..., description='Sequence name')
    pattern: str | None = Field(None, description='Pattern with {n} placeholder')
    start: int | None = Field(1, description='Starting value')


class AssertionSpec(ExtensionModel):
    name: str = Field(..., description='Assertion name')
    signature: str | None = Field(None, description='Function signature')
    checks: str | None = Field(None, description='What this assertion checks')
    failure_message: str | None = Field(None, description='Message format on failure')
    negated_name: str | None = Field(
        None, description='Name of negated version (if exists)'
    )
    description: str | None = None


class Category(Enum):
    unit = 'unit'
    integration = 'integration'
    e2e = 'e2e'
    property = 'property'
    snapshot = 'snapshot'
    contract = 'contract'
    performance = 'performance'


class TestPatternSpec(ExtensionModel):
    name: str = Field(..., description='Pattern name')
    category: Category | None = Field(None, description='Pattern category')
    applies_to: list[str] | None = Field(
        None, description='Types/features this pattern applies to'
    )
    setup: str | None = Field(None, description='Setup instructions')
    example: str | None = Field(None, description='Example test code')
    fixtures_used: list[str] | None = Field(None, description='Fixtures typically used')
    description: str | None = None


class TestDoubleSpec(ExtensionModel):
    provided: bool | None = Field(
        None, description='Whether library provides a test double'
    )
    type: str | None = Field(None, description='Test double type reference')
    builder: str | None = Field(None, description='Builder function reference')
    configurable_behaviors: list[str] | None = Field(
        None, description='Behaviors that can be configured'
    )


class Tool(Enum):
    coverage_py = 'coverage.py'
    pytest_cov = 'pytest-cov'
    istanbul = 'istanbul'
    jacoco = 'jacoco'
    custom = 'custom'


class CoverageTargetSpec(ExtensionModel):
    path: str | None = Field(None, description='Path or module')
    minimum: confloat(ge=0.0, le=100.0) | None = Field(
        None, description='Minimum coverage percentage'
    )


class TestingTypeFields(ExtensionModel):
    testable: bool | None = Field(
        None, description='Whether type is designed for testing'
    )
    test_double: TestDoubleSpec | None = None
    golden_tests: list[str] | None = Field(
        None, description='Golden test file references'
    )


class FactorySpec(ExtensionModel):
    name: str = Field(..., description='Factory name')
    model: str = Field(..., description='Model type this creates')
    fields: list[FactoryFieldSpec] | None = Field(None, description='Field definitions')
    traits: list[TraitSpec] | None = Field(None, description='Named trait variations')
    sequences: list[SequenceSpec] | None = Field(
        None, description='Sequence generators'
    )
    subfactories: list[str] | None = Field(None, description='Related subfactories')
    lazy_attributes: list[str] | None = Field(
        None, description='Lazily evaluated attributes'
    )
    description: str | None = None


class CoverageSpec(ExtensionModel):
    tool: Tool | None = Field(None, description='Coverage tool')
    targets: list[CoverageTargetSpec] | None = Field(
        None, description='Coverage targets'
    )
    exclude_patterns: list[str] | None = Field(
        None, description='Patterns to exclude from coverage'
    )
    branch_coverage: bool | None = Field(
        None, description='Whether branch coverage is tracked'
    )


class TestingLibraryFields(ExtensionModel):
    fixtures: list[FixtureSpec] | None = Field(
        None, description='Test fixture definitions'
    )
    mocks: list[MockSpec] | None = Field(None, description='Mock/stub utilities')
    factories: list[FactorySpec] | None = Field(None, description='Test data factories')
    assertions: list[AssertionSpec] | None = Field(
        None, description='Custom assertions'
    )
    test_patterns: list[TestPatternSpec] | None = Field(
        None, description='Recommended test patterns'
    )
    coverage: CoverageSpec | None = None
